//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "member_family_relations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub person_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub relative_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub relation_type: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::members::Entity",
        from = "Column::PersonId",
        to = "super::members::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Members2,
    #[sea_orm(
        belongs_to = "super::members::Entity",
        from = "Column::RelativeId",
        to = "super::members::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Members1,
}

impl ActiveModelBehavior for ActiveModel {}
