//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod announcements;
pub mod attendance_records;
pub mod attendance_students;
pub mod member_family_relations;
pub mod members;
pub mod student_exams;
pub mod student_infos;
pub mod students;
pub mod teacher_assignments;
pub mod teachers;
