//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::announcements::Entity as Announcements;
pub use super::attendance_records::Entity as AttendanceRecords;
pub use super::attendance_students::Entity as AttendanceStudents;
pub use super::student_grades::Entity as StudentGrades;
pub use super::students::Entity as Students;
pub use super::teachers::Entity as Teachers;
