//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "teacher_assignments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub teacher_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub student_id: Uuid,
    pub assigned_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::students::Entity",
        from = "Column::StudentId",
        to = "super::students::Column::MemberId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Students,
    #[sea_orm(
        belongs_to = "super::teachers::Entity",
        from = "Column::TeacherId",
        to = "super::teachers::Column::MemberId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Teachers,
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
