//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "attendance_students")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub attendance_record_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub student_id: Uuid,
    pub attendance_status: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::attendance_records::Entity",
        from = "Column::AttendanceRecordId",
        to = "super::attendance_records::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AttendanceRecords,
    #[sea_orm(
        belongs_to = "super::students::Entity",
        from = "Column::StudentId",
        to = "super::students::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Students,
}

impl Related<super::attendance_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttendanceRecords.def()
    }
}

impl Related<super::students::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Students.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
